{% set name = "qtmodern" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d433a54fbb400d49790aff65d35f203de2a8cc67795ac5bb04c5e766433fafae

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - qtpy

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - qtmodern
  commands:
    - pip check

about:
  home: https://github.com/gmarull/qtmodern
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PyQt/PySide Widgets Modern User Interface
  description: |
    qtmodern is a Python package aimed to make PyQt/PySide applications look
    better and consistent on multiple platforms. It provides a custom frameless
    window and a dark theme. In order to be compatible with multiple Python Qt
    wrappers QtPy is used.

extra:
  recipe-maintainers:
    - hmaarrfk
